# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "mpt3sas" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "zfs" ];
  boot.zfs.devNodes = "/dev/disk/by-id";
  boot.loader.grub = {
    enable = true;
    zfsSupport = true;
    efiSupport = true;
    efiInstallAsRemovable = true;
    mirroredBoots = [
      { devices = [ "nodev"]; path = "/boot1"; }
      { devices = [ "nodev"]; path = "/boot2"; }
    ];
  };


  fileSystems."/" =
    { device = "osdisk/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "osdisk/nix";
      fsType = "zfs";
    };

  fileSystems."/var" =
    { device = "osdisk/var";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "osdisk/home";
      fsType = "zfs";
      neededForBoot = true;
    };
  fileSystems."/data/files" =
    {
      device = "data/files";
      fsType = "zfs";
      encrypted.keyFile = "/root/zfs-data.key";
    };
  fileSystems."/data2/files" =
    {
      device = "data2/files";
      fsType = "zfs";
      encrypted.keyFile = "/root/zfs-data2.key";
    };


  fileSystems."/boot1" =
    { device = "/dev/disk/by-uuid/7821-EDA9";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/boot2" =
    { device = "/dev/disk/by-uuid/7824-6948";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault false;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
