vaultwarden:
    admintoken: ENC[AES256_GCM,data:9SzKhQKba+5TeUqKZxXYJtdpVUrG9BRx+EvEVlFctbBFR8e9bomk2tqUmjtVnIb0a2UKgr9TUIdkFeQ0o9AXgEXgZfOeODOJKpSjVPptdaXW1/Znx5NgLVPefr7XL8+/wUBfbYbo2iwPKq4pxpi2/4Y6QcgVhiv2RU+zQ0CLTbyz4MvT5YaFuedt,iv:w/wabkSUGR8lmAK+r1M/ntQNwfH+I2fw8P1igdSYLgQ=,tag:c6gfek5fjPxC51M3As+hAw==,type:str]
    dbuser: ENC[AES256_GCM,data:EGdfMDPmjDLeRLU=,iv:6Tr1cifOpSyTyrDqGOeaKSqYk9rQ0vd+nrkHldyGYGo=,tag:fmIMPFIL8u9FOXmBgFP9TQ==,type:str]
    dbpass: ENC[AES256_GCM,data:X0p+fQj8vxMF6mhRLH5pJg==,iv:lHP4M8C5zmY6vzh0i4q3EmIJFHYHGLrONtmSXeT2+ho=,tag:s+pQ0YoT1/wDDnJt96R/mA==,type:str]
teslamate:
    enckey: ENC[AES256_GCM,data:DJezDp7/u7WWtFfPkVzWO4F/6JYk+uGn6NP4ufwVECzEz3iq4fZIaacw8xRaGBabWhgIRj9tg1Fr4n6Bf9AEnBQ+aAIelgJMitL70Y/QEsskuQ6SlFTUAZLecbjoZ2H/nsnitE7TDEE6o/0BDON6xUeXYXi6T39CoLwwX4UARcaG9Pe6I6lw3AJyWu4ZWm82EBOqbv9soqNwFmiFQ/j03QNBJy/EMqnF4DJLIg7G2K3lnRAcRr6QErmY0AtgDAg2o/0SQGD3Q64sJBEksmAzb/Ar56cO9V65SjrW3WQDthq4zjASL2p6swAxVisl3094xiKjNASjUOQoHdqmPX35HnCstl1R3iQ9FsuHe/4zDFUsWcNRgUQiYHiuK8Nz4FxSzBytJwppTvflB18Ot2pVQp+kHw==,iv:r1H/S+FyiTV6+DwSQVAkIehLS1tcBXEaNzB30d8A9yo=,tag:XD51jj4IJSNv7Y1TL1/ddQ==,type:str]
    dbuser: ENC[AES256_GCM,data:FOnuqStfzA+m,iv:BciuzVNwZqfFcV8gv+6h16J3Qh19uDuTtCzlmXBzM6k=,tag:mhSHb79qFLr09AcLvSgDIg==,type:str]
    dbpass: ENC[AES256_GCM,data:JVFozYNHfm3dwRVh9RE08y7YPMb6bfMXVF5irmN45Kw=,iv:hhMNmjy+Lmor+2hoKWdcxJv3JBy+Afo1L97GoqyDGKc=,tag:dJthxEaiIjDr+vhXWDhT2A==,type:str]
    mqttuser: ENC[AES256_GCM,data:FggjbWwymH1R,iv:QJNef0b3UQ3iBXgsB3IAZ3D2QyPCZ86Iu1oCIE07dX0=,tag:KxI3myU0NV44aEZsjHqXrA==,type:str]
    mqttpass: ENC[AES256_GCM,data:+pmfBeNn+++hBUinwYaNN5tEGJOAatcGe7LBmK1QAg0=,iv:xqhwceCSEZjBDAfbmc7A0fV2jBNkC07BWD8ro1bTApU=,tag:olE3fRJU7Nx5Zmpriq9wpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15k0qtgxzppsfrh8h8x08zw2qd0nxdumdhlxe3yqwpx8z3y3rn5yshwkvjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeFU4eXdXUTEzWGFCZUdR
            RkZoa0dzMzg2aHc0bS9LbUNGUnZiTzE0SkZ3Cnp4UWttYUFKdUVidU1JM3pJNTJj
            cENGMTZxajVzN0FQNW5zZW14eEx4UUUKLS0tIFRUbjczSis1cFdBZ2RwTVdJMnd5
            NHYrTC9QVUowVTF0bTZGeFByVG9PdkEKUiF1TSS7hzckT2qMscrWoPG2OdYcHoKR
            Qy7prZ4DA55Dk1mhg0m8vc3Dg36bBvqXk/eJJ3EfsLZAP1IPjtuC1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16pxhjh47yzlz8umdpu6rt6f2s2z5gmkvvqrh6g0hl53kjqe3pgcslugkvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Qmw4SFE1VWVLMzdRZitJ
            SnhXUXlyblQ2WG9xbEEyNEYwdC9ZZEZlSnprCkNiWitPaDdtajZ2bDR6OVdiTlRX
            OHZ3RjFPeGxLbXh5MlRuQ01NTU4vNzgKLS0tIEZZWVBndFFXTGZkQ0U3OHlkMGlW
            NUNNdm5HZ2xMNHVHbGxYRUZLVUVxb00KWcc1jKnslIsm8cgVn2k/8nHz9yq0YrL9
            RkbsB2BMkycJXU7VRohJG2S2nJ+MKgsF+eRUovEbHjYdtTO/AukWCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-11T10:36:23Z"
    mac: ENC[AES256_GCM,data:Kl/WniJHNwnNK0JwNSzQAtvbdEuGX0dPzcyXXk9URpz6Q/zcHWhSRkIwlSu2n1TKupiS0CsXQKvDB8XrpM7gj3b6s3hqSJ5dE3fzn8sYcC2ckbUIkNM6xfqgU8iuGE18qo2uGI0MHrX1edDZjbGRdyU9zsyabgbDMTYLpQ9TIKU=,iv:X6+pQwzvJbqP8/MzbxWBcaGeNEmluYCnI7F2wnyLTXI=,tag:XEY2kWobr7uuozqsBJHvCg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
