freshrss-password: ENC[AES256_GCM,data:15e+ARaxxFZ5r2cu3LGtK23fpV3sxn7EsgTd3CzYvE8=,iv:RC/rRGJalvZS+RZpCwMGKjun1K7amjz7t1HnzvaN5kw=,tag:VRWV1UL3zg3bKomu9PzHQQ==,type:str]
sops:
    age:
        - recipient: age15k0qtgxzppsfrh8h8x08zw2qd0nxdumdhlxe3yqwpx8z3y3rn5yshwkvjh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVDBnN3JvQkpZVVgwcW5B
            cHg3dXFuTldvNEwxaG1NSGJGaXlFV1BFWkJVClZSQTJqSC9aN0Vrd0xZSkErOGZQ
            blVSL3JiWFg3ZGptc2FJaC9oRTdpMFEKLS0tIFZUQzRIQmpuaC81bGRvWk1adGVJ
            SE9rZ1VZTFlJelJld09rdHUxeUxBTkkKyalxXzUUASMnQ8mPr8i7OJozsgKZ4myu
            KwzaIcsRarcRyfeWisO4vUu+s/hwuaYhMI28PDSWfzfHMejd0/Myzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16pxhjh47yzlz8umdpu6rt6f2s2z5gmkvvqrh6g0hl53kjqe3pgcslugkvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4czcrWGluWWw0V3FXV2NR
            ZEFKOENCUmNPVkdSUDMzcEJxQno0Z0E1UWpjCjdhTkU5NGpwK1YzMHM3VlFxU1lj
            T1dhYSsrMW9MOCtPa3dibnh5MWhweHMKLS0tIGVrdG9TZ01hQklaSHJIRUdhNzVq
            RXFhRzVKaTZNRmd2ajRnbVlxdllkZWMKx7xoFgPOZcJZz8+2CFA1JHX0jFYE/9qz
            x/0p2DqARJ74ltJ28qA+EkC6WNe8V5zCaiav2ICSK5YcwckkHbn56Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T20:47:54Z"
    mac: ENC[AES256_GCM,data:RgSD6TJpUYPY8IWqFmZrxmVezjAA8RKBr3B9akyMJ83WBEN5w+sdp1lX5Avjo4xmXBgXz/EHlPp6Mah1/ceEjQcCD4jRsFXT2eQ9k2wtLN78a2m6J053Lm/adeI0/Ww1QAgfIsgOfJ/vWq7NDaeeTOS/PcivH0m0JEnQji8q1qc=,iv:2e8Iv4EY1xG6Wz7XT4V+cek8s9HPHELfPOuHFsbIaRA=,tag:vPqdC1kK60PixjchAiBOgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
