freshrss-password: ENC[AES256_GCM,data:15e+ARaxxFZ5r2cu3LGtK23fpV3sxn7EsgTd3CzYvE8=,iv:RC/rRGJalvZS+RZpCwMGKjun1K7amjz7t1HnzvaN5kw=,tag:VRWV1UL3zg3bKomu9PzHQQ==,type:str]
grafana-secret-key: ENC[AES256_GCM,data:/ATqLG1+zA+HS07+8jm9+3BJgHDPQVkLaymoKwurkHsT0F9ItsKjuCTIGx4=,iv:yqCE5ZM/C5E7QYdVGbZK43OF9JfevE8Dhab7Rd5oZMk=,tag:2LKN3oOCG5AW8fVHNi3wqg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVDBnN3JvQkpZVVgwcW5B
            cHg3dXFuTldvNEwxaG1NSGJGaXlFV1BFWkJVClZSQTJqSC9aN0Vrd0xZSkErOGZQ
            blVSL3JiWFg3ZGptc2FJaC9oRTdpMFEKLS0tIFZUQzRIQmpuaC81bGRvWk1adGVJ
            SE9rZ1VZTFlJelJld09rdHUxeUxBTkkKyalxXzUUASMnQ8mPr8i7OJozsgKZ4myu
            KwzaIcsRarcRyfeWisO4vUu+s/hwuaYhMI28PDSWfzfHMejd0/Myzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15k0qtgxzppsfrh8h8x08zw2qd0nxdumdhlxe3yqwpx8z3y3rn5yshwkvjh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4czcrWGluWWw0V3FXV2NR
            ZEFKOENCUmNPVkdSUDMzcEJxQno0Z0E1UWpjCjdhTkU5NGpwK1YzMHM3VlFxU1lj
            T1dhYSsrMW9MOCtPa3dibnh5MWhweHMKLS0tIGVrdG9TZ01hQklaSHJIRUdhNzVq
            RXFhRzVKaTZNRmd2ajRnbVlxdllkZWMKx7xoFgPOZcJZz8+2CFA1JHX0jFYE/9qz
            x/0p2DqARJ74ltJ28qA+EkC6WNe8V5zCaiav2ICSK5YcwckkHbn56Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16pxhjh47yzlz8umdpu6rt6f2s2z5gmkvvqrh6g0hl53kjqe3pgcslugkvg
    lastmodified: "2026-06-20T14:23:29Z"
    mac: ENC[AES256_GCM,data:z/c/uTSCtV7qHWJPZ6CEHf4x9vVwdcXGPQoZrKZD/DJysRQEsBA6fPKP4iw0vfb43enFXrI+ogHC8t4LYNzDumc7C3fHxZjN7hA8mLVp4WPxCFKaOutrPcMSgot1FWeLFBpcEJEZCJbfpM3pSMj2qPMnYIMCUxwoaIvyGizZwjQ=,iv:1sN0AYNPCdegvXVQ8XriHeiSkOsatQUtvyVs8IfmLiM=,tag:aCRnEbUWr3DroyKL6QEq3w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
